spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.176.168:3306/JhcManage?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 3171276371@qq.com
    password: nxogttqexpjhdgbe
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: utf-8
logging:
  level:
    cxt.cn: debug


